project:
  type: website

website:
  title: "Diana Rodriguez" 
  site-url: https://diana-rodriguez.de
  description: "This is Diana Rodriguez's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/diana-c-rodriguez.github.io
      - icon: twitter
        href: https://
      - icon: youtube
        href: https://
format:
  html:
    theme: theme.scss

