project:
  type: website

website:
  title: "Diana-C-Rodriguez.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: About
      - href: Research.qmd
        text: Research
      - href: Project.qmd
        text: Project
      - href: CV.qmd
        text: CV
      - href: Fall.R.qmd
        text: Fall.R

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual




