project:
  type: website

website:
  title: "diana-c-rodriguez.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: CV.qmd
        text: CV
      - text: EPPS6356 assignments   
        menu: 
          - assignments.qmd
          - Assignment2.qmd
          - Assign3.qmd
          - Assign4.qmd
          - Assign5.qmd
      
        
      - href: https://Diana-C-Rodriguez.github.io/Diana-C-Rodriguez.github.io-blog
        text: blog
      - href: https://diana-c-rodriguez.shinyapps.io/Shiny1/?_ga=2.254884232.181556009.1667238624-657830594.1667238624
        text: Shiny 
        
      - text: EPPS6302 Assignments
        menu: 
          - assign02.qmd
          
        


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual






