project:
  type: website

website:
  title: "Diana-C-Rodriguez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: CV.qmd
        text: CV
      - href: assignments.qmd
        text: Assignments
      - href: Assignment2.qmd
        text: assignment2
      - href: https://Diana-C-Rodriguez.github.io/blog/index.htm
        text: blog
      
        


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual






