project:
  type: website

website:
  title: "diana-c-rodriguez.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: CV.qmd
        text: CV
      - href: assignments.qmd
        text: Assignments
      - href: Assignment2.qmd
        text: assignment2
      - href: Assign3.qmd
        text: assignment3
      - href: Assign4.qmd
        text: Assignment4
      - href: https://Diana-C-Rodriguez.github.io/Diana-C-Rodriguez.github.io-blog
        text: blog
      
        


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual






