---
title: "CV"
---

**EDUCATION**

THE UNIVERSITY OF TEXAS AT DALLAS

Doctor of Philosophy in Criminology- Current -

-   Member of the Criminology Graduate Student Association
-   3.8 GPA
-   Teaching Assistant for Undergraduate Courses: Introduction to Criminal Justice; Guns and Crime in Criminal Justice o Instructor of Course: Advanced Criminology; Criminal Law
-   Received "exceeded expectation" in every TA evaluation category
-   Exclusively received positive student reviews as instructor of course(s)

UNIVERSITY OF HOUSTON- DOWNTOWN

-   Masters of Science in Criminal Justice, December 2020
-   Member of the Alpha Phi Sigma National Honor Society
-   3.9 GPA
-   Professor Assistant for Freshman Seminar- University of Houston-Downtown
-   Research development student (Determinate Sentencing/Peer Mediation)
-   Criminal Justice Service Excellence Award recipient - University of Houston-Downtown

UNIVERSITY OF HOUSTON- DOWNTOWN

Bachelor of Science in Criminal Justice, December 2014 - Focus of studies in Juvenile Justice - Minor in Spanish - Oral presentation and literature

**WORK EXPERIENCE**

Lone Star College -- Montgomery August 2022- Current Adjunct Professor Undergraduate Course in Criminal Justice: Introduction to CJ

The Woodlands, TX

-   Provide instruction through duo modalities (in-person/online)
-   Create course curriculum, syllabus, and calendar
-   Explain course work and provide guidance to students based on individual needs
-   Grade assignments and report grades adhering to campus policy
-   Host tutoring session and office hours for students according to student needs and schedules
-   Respond to student concerns and needs for accommodations with equity and fair treatment

The University of Texas at Dallas August 2021- Current

Teaching Assistant Undergraduate Courses in Criminal Justice: Introduction to CJ; Guns and Crime in CJ; Advanced Criminology (instructor); Criminal Law (instructor) Richardson, TX - Create course curriculum, syllabus, and calendar

-   Explain course work and provide guidance to students based on individual needs
-   Grade assignments and report grades adhering to campus policy
-   Host tutoring session for students according to student needs and schedules
-   Primary point of contact for students
-   Respond to student concerns and needs for accommodations with equity and fair treatment
-   Create extra credit assignments for students

Harris County Juvenile Probation July 2017 -- August 2021 Renew, Inspire, Support, Empower (RISE) Program Community Unit Probation Services (CUPS4) 2017-2018 Community Unit Probation Services (CUPS9) 2018-2019 Court 360- Specialized Court Probation Officer (2019-2020) Houston, Texas

-   Co-creator and facilitator for RISE Youth Town Hall/ RISE Life Skills Programs.
-   Develop creative case plan goals using evidence-based practices.
-   Maintain Texas Department of Criminal Justice practice standards.
-   Develop relationships with community programs, schools, and rehabilitative programs.
-   Communication with clients, attorneys, and courts personnel.
-   Assess for individualized needs of youths and their families and provide appropriate resources.
-   Maintained knowledge regarding Juvenile codes and Texas Education Agency Policies.

Harris County- TRIAD January 2016 -- July 2017 Justice of the Peace Court Liaison Program Specialist community program development, triage services, education services Houston, Texas

-   Provided individualized resource information according to needs of at-risk youths and their families.
-   Developed relationships with community programs, schools, and rehabilitative programs.
-   Remained informed regarding Juvenile Justice Code, and Texas Education Agency policies.
-   Developed Community based programs (Teen Awareness).
-   Demonstrated leadership skills, resulting in program specialist responsibilities.

Department of Family and Protective services (DFPS) 2015- 2016 Investigator Houston, Texas

-   Prepared necessary documents for the court systems.
-   Investigated allegations of abuse or neglect to determine safety of children.
-   Completed DFPS Academy Training (120 hours).
-   Accurately documented investigations, and provided detailed information in written and oral form.
-   Maintained consistent contact with clients and colleagues.

Justice of the Peace- Court Clerk 2012- 2015 Juvenile Criminal Court Clerk Houston, Texas

-   Drafted pleadings, motions, oppositions, and court orders.
-   Provided families with information regarding court proceedings.
-   Interpretation Aid for Spanish speaking families.
-   Developed relationships with prosecutors and community support programs.
-   Maintained knowledge regarding Juvenile codes and Texas Education Agency Policies.
-   Developed relationships with at-risk youth, parents, and school personnel.

**PROFESSIONAL TRAINING**

Restorative conference facilitator training (April 2022) Center for Restorative Justice and Peacemaking

Grant Writing Certification (current) The University of Texas at Dallas

**ACADEMIC RESEARCH**

A review of restorative justice in U.S. schools -- Academic article (work in progress) The University of Texas at Dallas

Peer Circles - Program Manual (work in progress) University of Houston-Downtown/ The University of Texas at Dallas

Fear of Crime According to Self-Identification of Femininity (work in progress) The University of Texas at Dallas

Continued research in the following fields of interest:

Restorative justice o Juvenile delinquency

Socioeconomic status and disparities in CJ

**PROFESSIONAL AFFILIATIONS**

ACADEMY OF CRIMINAL JUSTICE SCIENCES National Organization - Student Member (current)

CENTER FOR RESTORATIVE JUSTICE AND PEACEMAKING (Current member)

**VOLUNTEER EXPERIENCE**

TRIAD "TEEN AWARENESS" FACILITATOR (2014-2016)

GUEST SPEAKER: TRUANCY - University of Houston Graduate Social Work Program (2015-2016)

WORK TEXAS- HORTICULTURE PROJECT (2019-2020)

PEER CIRCLES PROGRAM Project Remix Charter School- Houston, TX- Pilot Program starting in 2020 (on-going)

**ORGANIZATIONS**

CRIMINOLOGY GRADUATE STUDENT ASSOCIATION The University of Texas at Dallas- Student Member/Board Member (current)

CO- LEAD FACILITATOR FOR IMPLICIT BIAS WORKSHOPS - BLOOMBERG AND ASSOCIATES Implicit Bias Culture of Data and Accountability team

Vice President of Alpha Sigma National Honor Society (2020-2021) Criminal Justice National Honor Society- University of Houston-Downtown

References: Upon request
