project:
  type: website

website:
  title: "Diana Rodriguez" 
  site-url: https://Diana-C-Rodriguez.github.io/blog
  description: "This is Diana Rodriguez's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://Diana-C-Rodriguez.github.io
      - icon: twitter
        href: https://
      - icon: youtube
        href: https://

